# Generated by Django 6.0.8 on 2026-09-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateur',
            name='role',
            field=models.CharField(choices=[('LIVREUR', 'Livreur'), ('RESPONSABLE', 'Responsable'), ('ADMIN', 'Administrateur')], default='LIVREUR', max_length=20),
        ),
    ]
