# Generated by Django 6.0.8 on 2026-09-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='date_naissance_patient',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='nom_patient',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
