name: CI

on:
  push:
    branches:
      - main

jobs:
  verifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14.7"

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Vérifier la configuration Django
        run: python manage.py check
        continue-on-error: true
